import rawSemanticMap from '../../content/semantic-map.json';
import type { Article } from './types';

/**
 * Build-time semantic-map artifact (#29), committed as
 * content/semantic-map.json and regenerated by `npm run build:semantic`.
 * The freshness gate (check:semantic, wired into gates:quality) guarantees it
 * matches the content at CI time; this module's guard is the RUNTIME safety
 * net that decides semantic-vs-curated fallback (decision 5a).
 */

/** One star's semantic placement. */
export interface SemanticStar {
  id: string;
  /** Rendered (mapped) constellation — may differ from the authored one. */
  constellation: string;
  x: number;
  y: number;
  /** Depth cue in [0, 1] — same contract as StarPosition.z (shell thickness). */
  z: number;
  /** True when the article sits in sparse space, outside its knot. */
  outlier: boolean;
  /** Cluster membership strength (cosine to centroid), in [-1, 1]. */
  strength: number;
}

/** Sparse similarity edge — becomes a curved, weight-carrying line. */
export interface SemanticEdge {
  a: string;
  b: string;
  weight: number;
}

export interface SemanticMap {
  schemaVersion: number;
  generatorVersion: number;
  model: string;
  seed: number;
  inputHash: string;
  stars: SemanticStar[];
  edges: SemanticEdge[];
}

/**
 * Structural guard over the imported artifact. Deliberately shallower than
 * scripts/semantic-lib.mjs's validateSemanticMap (the gate owns full
 * validation); this checks exactly what the runtime consumes, because its
 * only job is the fallback decision — a malformed map must degrade to the
 * curated layout, never crash the render.
 */
export function isSemanticMap(v: unknown): v is SemanticMap {
  if (typeof v !== 'object' || v === null) return false;
  const m = v as Record<string, unknown>;
  if (!Array.isArray(m.stars) || m.stars.length === 0 || !Array.isArray(m.edges)) return false;
  for (const s of m.stars) {
    if (typeof s !== 'object' || s === null) return false;
    const star = s as Record<string, unknown>;
    if (
      typeof star.id !== 'string' ||
      typeof star.constellation !== 'string' ||
      typeof star.x !== 'number' ||
      !Number.isFinite(star.x) ||
      typeof star.y !== 'number' ||
      !Number.isFinite(star.y) ||
      typeof star.z !== 'number' ||
      star.z < 0 ||
      star.z > 1 ||
      typeof star.outlier !== 'boolean' ||
      typeof star.strength !== 'number'
    ) {
      return false;
    }
  }
  for (const e of m.edges) {
    if (typeof e !== 'object' || e === null) return false;
    const edge = e as Record<string, unknown>;
    if (
      typeof edge.a !== 'string' ||
      typeof edge.b !== 'string' ||
      typeof edge.weight !== 'number' ||
      !Number.isFinite(edge.weight) ||
      edge.weight <= 0 ||
      edge.weight > 1
    ) {
      return false;
    }
  }
  return true;
}

/** Static import + guard. Null ⇒ the app falls back to CuratedForceLayout. */
export function loadSemanticMap(): SemanticMap | null {
  return isSemanticMap(rawSemanticMap) ? rawSemanticMap : null;
}

/** True when every article has a star in the map (stale maps fall back). */
export function coversArticles(map: SemanticMap, articles: readonly Article[]): boolean {
  const ids = new Set(map.stars.map((s) => s.id));
  return articles.every((a) => ids.has(a.id));
}

/**
 * Display-grouping override (#29 decision 3a): articles render under their
 * SEMANTIC constellation — colors, legend, list groups, catalog numbering,
 * and globe figures all follow one mapping — while frontmatter keeps the
 * authored value as authoring truth. Article objects are reused unless the
 * constellation actually changes.
 */
export function applySemanticConstellations(
  articles: readonly Article[],
  map: SemanticMap,
): Article[] {
  const byId = new Map(map.stars.map((s) => [s.id, s.constellation]));
  return articles.map((a) => {
    const c = byId.get(a.id);
    return c === undefined || c === a.constellation ? a : { ...a, constellation: c };
  });
}
